CREATE TYPE "public"."ticket_categoria" AS ENUM('Contabilidad', 'Documento faltante', 'Error del sistema', 'Solicitud', 'Otro');--> statement-breakpoint
CREATE TYPE "public"."ticket_estado" AS ENUM('Abierto', 'En curso', 'En espera', 'Resuelto', 'Cerrado');--> statement-breakpoint
CREATE TYPE "public"."ticket_prioridad" AS ENUM('Baja', 'Media', 'Alta', 'Urgente');--> statement-breakpoint
CREATE TABLE "ticket_mensajes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ticket_id" uuid NOT NULL,
	"usuario_id" uuid NOT NULL,
	"cuerpo" text NOT NULL,
	"es_interno" boolean DEFAULT false NOT NULL,
	"creado_en" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tickets" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"numero" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "tickets_numero_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"firma_contable_id" uuid NOT NULL,
	"empresa_id" uuid,
	"usuario_creador_id" uuid NOT NULL,
	"asignado_a_id" uuid,
	"categoria" "ticket_categoria" NOT NULL,
	"prioridad" "ticket_prioridad" DEFAULT 'Media' NOT NULL,
	"estado" "ticket_estado" DEFAULT 'Abierto' NOT NULL,
	"titulo" text NOT NULL,
	"descripcion" text NOT NULL,
	"periodo_tributario" text,
	"detalle" jsonb,
	"resuelto_en" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "ticket_mensajes" ADD CONSTRAINT "ticket_mensajes_ticket_id_tickets_id_fk" FOREIGN KEY ("ticket_id") REFERENCES "public"."tickets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ticket_mensajes" ADD CONSTRAINT "ticket_mensajes_usuario_id_usuarios_id_fk" FOREIGN KEY ("usuario_id") REFERENCES "public"."usuarios"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_firma_contable_id_firmas_contables_id_fk" FOREIGN KEY ("firma_contable_id") REFERENCES "public"."firmas_contables"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_empresa_id_empresas_id_fk" FOREIGN KEY ("empresa_id") REFERENCES "public"."empresas"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_usuario_creador_id_usuarios_id_fk" FOREIGN KEY ("usuario_creador_id") REFERENCES "public"."usuarios"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_asignado_a_id_usuarios_id_fk" FOREIGN KEY ("asignado_a_id") REFERENCES "public"."usuarios"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ticket_mensajes_ticket_creado_idx" ON "ticket_mensajes" USING btree ("ticket_id","creado_en");--> statement-breakpoint
CREATE UNIQUE INDEX "tickets_numero_unique" ON "tickets" USING btree ("numero");--> statement-breakpoint
CREATE INDEX "tickets_firma_estado_idx" ON "tickets" USING btree ("firma_contable_id","estado");--> statement-breakpoint
CREATE INDEX "tickets_asignado_estado_idx" ON "tickets" USING btree ("asignado_a_id","estado");